separator=false
markup=pango
color=#717171
color=default

[memory]
label= 
command=free -h | awk 'match($0, /^Mem/){print $3 " / " $2}'
color=default
interval=1

[time]
command=date '+%b %d日(%a) %H:%M:%S'
interval=1

[ip]
command=ip a | awk '{print $1,$2}'|grep -a "inet 192*"|sed -e 's/inet/local/g '
interval=once
color=#91E78B

[simple-2]
full_text= 
color=#717171

