;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #00232432
background-alt = #00aa232432
foreground = #ffffff
primary = #ffffffff
secondary = #8ABEB7
alert = #A54242
disabled = #707880
barbg = #00000000
[bar/statusbar]
monitor = ${env:MONITOR:}
width = 98%
height = 20pt
radius = 4
offset-x = 1%
offset-y = 0.4%
; dpi = 96
#fixed-center = true
background = ${colors.background}
foreground = ${colors.foreground}

line-size = 6pt

border-size = 0 pt
border-top = 0 pt
border-bottom = 2pt
border-color = #407c7e984
padding-left = 8pt
padding-right = 8pt
padding-top = 4
padding-bottom = 1pt
margin-top = 0
module-margin = 0

separator =" | "
separator-foreground = ${colors.disabled}

font-0 = HackGen Console NF:weight=bold:pixelsize=12;

modules-left = xworkspaces
modules-center = date
modules-right = wlan cpu memory swap tray pulseaudio

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

#tray-position = right

# wm-restack = generic
# wm-restack = bspwm
wm-restack = i3
override-redirect = true

[module/i3]
type = internal/i3
show-urgent = true
pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-click = true
fuzzy-match = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/tray]
type = internal/tray
format-margin = 4px;
tray-spacing = 4px;

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = 󰖁 
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/swap]
type = internal/memory
interval = 3
format = <label-swap-used>
label-swap-used = SWAP %percentage_swap_used%%


[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected =  %essid% | 󱚸 %signal%% 󰹺 %netspeed%


[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
label-active-underline= ${colors.primary}

[module/bat]
type = custom/script
exec = ~/dotfiles/polybar/bat.sh
tail = true
interval = 20

[module/date]
type = internal/date

interval = 1.0

date = %H:%M 
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = FFFFFF

#[module/i3-volume]
#type = custom/script
#tail = true
#label = %output%
#exec = ~/dotfiles/polybar/volume listen "%i %v %p\n"
#scroll-up = ~/dotfiles/i3/volume up
#scroll-up = ~/dotfiles/i3/volume down
#click-left = ~/dotfiles/i3/volume mute
#click-right = exec pavucontrol &

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
